### ISSUE TITLE
uint64 VersionCode

### ISSUE THREAD

**Issue by 89z** [kamushadenes/apkrash#1]
Hey, I noticed you have to do a cast here:

https://github.com/kamushadenes/apkrash/blob/887b44d8f15d60ca1d69bfa24710ac50e8cc2bc5/store/main.go#L62-L65

this is unintentional, I have fixed it:

https://github.com/89z/googleplay/blob/v1.8.1/header.go#L45

**Comment by kamushadenes** [comment]
Much appreciated, will update soon.
